version: '3.5'
networks:
  stan-network:
    name: stan-network
    driver: bridge

services:
  db_auth:
    container_name: db_WbTech0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
      - POSTGRES_DB=db_WbTech0
      - PGDATA=/var/lib/postgresql/data
    image: postgres:16.1
    volumes:
      - db:/var/lib/postgresql/data
  stan-server:
    networks:
      - stan-network
    image: nats-streaming
    ports:
      - "4222:4222"
      - "8222:8222"
    command:
      - "-cid"
      - test_cluster
#  publisher:
#    networks:
#      - stan-network
#    build:
#      context: ${PWD}/../../Main
#    depends_on:
#      - stan-server
#    volumes:
#      - ${PWD}/model.json:/bin/model.json
#  subscriber:
#    networks:
#      - stan-network
#    depends_on:
#      - stan-server
volumes:
  db:

